client/src/index.js
=> Commit Prueba

api/src/routes/index.js, api/src/routes/middleware/models/CRUDProduct.js, api/src/routes/middleware/models/CRUDUser.js, api/src/routes/middleware/productFunct.js, api/src/routes/middleware/userFunct.js, api/src/routes/productRoute.js, api/src/routes/userRoute.js
Chicos, deje las rutas definidas, modularice y deje comentarios para que se guien en cada carpeta, en routes/ esta el index.js, productRoute.js y userRoute.js. En routes/middleware esta definida productFunc.js y userFuncs.js que van a servir de intermediarios. y en routes/moddleware/models esta definida CRUDProduct.js y CRUDUser.js, donde se va a definir toda la logica pura.
=> feat(routes): add modularization

api/src/models/User.js, api/src/routes/middleware/models/CRUDProduct.js, api/src/routes/middleware/productFunct.js, api/src/routes/productRoute.js
Se crearon las rutas de obtener todos los productos y por nombre
=> "Rutas Get Products"

api/src/routes/productRoute.js
se hizo la ruta put para actualizar si el producto esta activo o no
=> "Ruta de put realizada"

client/package.json, client/src/Components/cards/Card.jsx, client/src/Views/Loading/Loading.jsx, client/src/Views/Menu/menu.jsx, client/src/Views/Menu/menu.module.css, client/src/components/cards/cards.module.css, client/src/index.js, client/src/redux/actions/actionsProducts.js, client/src/redux/actionsType/productsAT.js, client/src/redux/reducer.js, client/src/redux/store.js
se hicieron los ajustes de funcionamiento del menú
=> "funcionalidades del menu"

api/src/routes/middleware/modules/CRUDUser.js
=> fix(post/user)

api/src/routes/middleware/modules/CRUDUser.js, api/src/routes/middleware/userFunct.js, api/src/routes/userRoute.js
rutas de user arregladas, se cambia la búsqueda de user por  id para búsqueda por mail
=> "Fix(User/get and post)"

api/__tests__/products.test.js, api/__tests__/users.test.js, api/package.json, api/src/database.js, api/src/models/Category.js, api/src/models/Product.js, api/src/routes/categoryRoute.js, api/src/routes/index.js, api/src/routes/middleware/modules/CRUDProduct.js, api/src/routes/productRoute.js
**ProductRout**
- Se instalo Jest para el manejo de test
- Se desarrollaron test para : productPost, getProduct.
- Se agregaron validaciones para modulePostProduct
- Se optimizaron algunas funciones de la ruta de productos.
**Modelo Category**
- Se elimino la propiedad "category" del modelo Products.js.
- Se agrego un nuevo modelo, Category.js
- Se relaciono el modelo Products y Category en mucho a muchos. " belongsToMany " 
- Se desarrollo la ruta POST para el modelo Category. Se pueden crear nuevas categorias.
- Se modifico la ruta POST de de productRoute, ahora recibe categoryId y las relaciona con los nuevos productos creados.
=> Se agrego, se modifico y se arreglo

api/index.js, api/src/routes/middleware/modules/CRUDProduct.js, api/src/routes/middleware/productFunct.js
-Se arreglo la ruta PUT, ahora recibe categoryId por body como un array de strings [ " " ] (puede recibir varios id)
-Ahora las rutas GET muestran categories : [ " " ] como un array de strings.
=> fix (api/productRoute): fix all GET request! & PUT

client/src/Components/dashboardCard/dashboardCard.jsx, client/src/Components/dashboardCardCont/dashboardCardCont.jsx, client/src/Components/dashboardCardCont/dashboardCardCont.module.css, client/src/Views/DashBoard/dashboard.jsx, client/src/components/searchBar/searchBar.module.css
Co-authored-by: LMCT04 <LMCT04@users.noreply.github.com>
=> avance de dashboard

client/src/components/searchBar/searchBar.jsx, client/src/redux/actions/actionsProducts.js, package.json
Search Bar solucionados bugs y mensaje de no se encontro producto
=> Search Bar

api/src/models/User.js, client/package.json, client/src/Views/Login/login.jsx, client/src/firebase/config.js, client/src/redux/actions/actionsUsers.js, client/src/redux/actionsType/usersAT.js, client/src/redux/reducer.js
se hizo la autentificacion de google
se hizo la ruta post user en reduz para crear el usurio
se ejecuto una accion para que cuando el usurio entre por gmail se guarde su usuario en el modelo users de postgress y asi no se pierda su info cada vez que entre.
Se ejecuto una accion para que solo se postee el gmail ingresado una sola vez
=> autentificaciongmail

api/src/routes/middleware/modules/CRUDUser.js, api/src/routes/middleware/userFunct.js, api/src/routes/userRoute.js, client/src/Components/CustomFileInput/CustomFileInput.jsx, client/src/Views/Form/form.jsx, client/src/firebase/config.js
queda listo la creación de usuarios y obtención de todos y por mail con el nuevo modelo
=> Juancho add image  fix

api/src/models/User.js, api/src/routes/middleware/modules/CRUDUser.js, api/src/routes/middleware/userFunct.js, api/src/routes/userRoute.js
Del modelo de usuario, se dejo fullname, userName, se quito name y lastname, y se deja que campos como age, addres , shoppingHistory y favorite, puedan ser null en la creacion de usuarios
=> "fix(api/scr/user):cambios en modelos y get y post de usuarios'

api/src/routes/middleware/modules/CRUDProduct.js
Ahora al crear recetas se necesita pasar los datos de image como un ARRAY  ["https://pbs.twimg.com/media/DK0PINwXoAECL22.jpg"] EJEMPLO
=> Fix de POST product

api/src/routes/middleware/modules/CRUDProduct.js, api/src/routes/middleware/productFunct.js, client/package.json, client/src/App.css, client/src/App.js, client/src/Views/Detail/detail.jsx, client/src/Views/UserProfile/FavoritesContent/FavoritesContent.jsx, client/src/Views/UserProfile/userProfile.css, client/src/Views/UserProfile/userProfile.jsx
Se instalo "formik-material-ui" para su uso en el nuevo componente.
Se creo el nuevo componente UserProfile.
Se creo un subComponente para UserProfile llamado FavoritesContent.
El nuevo componente se renderiza en la ruta /profile
=> Se creo el componente UserProfile

api/src/database.js, api/src/models/CartProduct.js, api/src/routes/middleware/modules/CRUDCart.js, api/src/routes/shoppingCartRoute.js
Se arreglaron funcionalidades de adicionar al carrito, remover de a un elemento del carrito y obtener el valor total y la cantidad de productos del carrito
con esto ya se puede usar la app, corre normalmente, faltaria solucionar remover todos los productos.
=> fix(shoppingCart)add_fix remove_fix getinfocart_fix

api/package.json, api/src/routes/productRoute.js, client/package.json, client/src/App.js, client/src/Components/Pay/Pay.jsx, client/src/Components/Pay/pay.module.css, client/src/Components/PayCarrito/PayCarrito.jsx, client/src/Components/PayCarrito/payCarrito.module.css, client/src/Components/cards/Card.jsx, client/src/Views/Cart/cart.jsx
=> Pasarela de Pagos

client/src/App.js, client/src/Components/BotonsCart/BotonsCart.jsx, client/src/Components/NavBar/navBar.jsx, client/src/Views/Cart/cart.jsx
Ajustes de carrito ya esta con pasarela de pagos , ya no causa problema si se borra el localstorage
=> fix(carrito)

client/package.json, client/src/Components/BotonsCart/BotonsCart.jsx, client/src/Components/Dash_Components/dashboardCard/dashboardCard.jsx, client/src/Components/cards/Card.jsx, client/src/Components/cartCard/cartCard.jsx, client/src/Views/Cart/cart.jsx, client/src/Views/Detail/detail.jsx, client/src/Views/Menu/menu.jsx
Con esto al parecer queda cerrado la parte de carrito
Se debe instalar una nueva dependencia sweetalert
npm install sweetalert
=> fix(cart) ultimos arreglos del carrito

client/src/Components/cards/Card.jsx
pequeño ajusta para deshabilitar pago y botones de add o remove del carrito , cuando se le hace borrado logico
=> fix(Card)arreglo para ocultar caracteristicas de la card deshabilitada

client/src/Components/CustomFileInput/CustomFileInput.jsx, client/src/Components/cardContainer/cardContainer.jsx, client/src/Components/cards/Card.jsx, client/src/Views/Detail/detail.jsx, client/src/Views/Form/form.jsx
Se arreglo el formulario de creacion
=> fix (form)

api/src/routes/productRoute.js, client/package.json, client/src/App.js, client/src/Views/Cart/cart.jsx, client/src/Views/Checkout/Checkout.jsx, client/src/Views/Form/form.jsx
Unos pequeños ajustes se eliminan lineas en el front
=> "Fix(Front) se eliminan lineas en el form que no se estanban usando
